name: Tareas Programadas de la Plataforma

on:
  schedule:
    # El flujo de trabajo se ejecutará CADA 5 MINUTOS.
    - cron: "*/5 * * * *"
  # También permite la ejecución manual
  workflow_dispatch:

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest

    steps:
      # Este paso obtiene la fecha actual para usarla en las condiciones 'if'
      - name: Get current minute
        id: date
        run: echo "minute=$(date +'%M')" >> $GITHUB_OUTPUT

      # --- Tarea 1: Se ejecuta siempre (cada 5 minutos) ---
      - name: Actualizar valores 'actual' del calendario
        run: |
          echo "Llamando a la Edge Function update-actual-values..."
          curl -X POST "${{ secrets.UPDATE_ACTUALS_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"

      # --- Tarea 2: Se ejecuta al inicio de la hora O manualmente ---
      - name: Escanear Señales de Trading
        if: fromJson(format('[{0}]', steps.date.outputs.minute))[0] < 5 || github.event_name == 'workflow_dispatch'
        run: |
          echo "Ejecutando tarea horaria o manual: signal-scanner..."
          curl -X POST "${{ secrets.SIGNAL_SCANNER_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"

      # --- Tarea 3: Se ejecuta al inicio de la hora O manualmente ---
      - name: Actualizar Calendario Económico Completo
        if: fromJson(format('[{0}]', steps.date.outputs.minute))[0] < 5 || github.event_name == 'workflow_dispatch'
        run: |
          echo "Ejecutando tarea horaria o manual: update-calendar..."
          curl -X POST "${{ secrets.UPDATE_CALENDAR_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"
            
      # --- Tarea 4: Se ejecuta al inicio de la hora O manualmente ---
      - name: Enriquecer Eventos con Descripciones
        if: fromJson(format('[{0}]', steps.date.outputs.minute))[0] < 5 || github.event_name == 'workflow_dispatch'
        run: |
          echo "Ejecutando tarea horaria o manual: enrich-events..."
          curl -X POST "${{ secrets.ENRICH_EVENTS_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"


